### ISSUE TITLE
export a Graph

### ISSUE THREAD

**Issue by ali1k** [Acubed/node-rdf#5]
How can I export a Graph as n3 or NT?

**Comment by Acubed** [comment]
The `Triple` object should have a `Triple#toString` method that serializes the object to an NT record.
Iterating over the triples in a graph, calling this method, can be used to produce an NT document.

So off the top of my head, this should work:

    var NT = graph.toArray().map(function(t){
        return t.toString() + "\n";
    }).join('');

... where `graph` is an instance of `Graph`.

Does that help?

**Comment by ali1k** [comment]
thanks. that helps me for now.
would be great if can add it as a method to Graph class too. 
or example to be able to do `graph.n3()` or `graph.toNT()`

**Comment by Acubed** [comment]
There is a whole section in RDF Interfaces on parsing and serializing data: http://www.w3.org/TR/2012/NOTE-rdf-interfaces-20120705/#rdf-data-interfaces

Unfortunately it doesn't play nicely with streams, e.g. you can't do partial writes. It's the whole document all-at-once.

And maybe these things are better suited for another package anyways. For instance, there's a dedicated Turtle parser package in Javascript (that's more compliant and faster than mine).

I'm looking to get the rdfjs community group to adopt work on RDF Interfaces though, for the primary reason of integrating streams support. If you have any thoughts I'd love to hear!

**Comment by ali1k** [comment]
I think the work @RubenVerborgh has done on streaming data would be very helpful here. However, as you said would be really great if RDFjs community accommodated it in RDF interfaces.

**Comment by RubenVerborgh** [comment]
So the work people are referring to here is [N3.js](https://github.com/RubenVerborgh/N3.js). It has a streaming parser and writer of N-Triples, N-Quads, Turtle, and TriG. It is implemented for maximal speed, but can be wrapped in other interfaces.

As an answer your question, you could do:
```
var writer = N3.Writer({ prefixes: { 'e': 'http://example.org/#' } });
graph.toArray().forEach(function(t){
    writer.addTriple(convertTriple(t));
});
writer.end(function (error, result) { console.log(result); });
```
In the above, `convertTriple` is a function that converts from the RDF interface format to [the N3.js triple representation](https://github.com/RubenVerborgh/N3.js#triple-representation).

**Comment by Acubed** [comment]
Ah yes. Thanks @RubenVerborgh!
